version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/user/src/cdd_vasa
    command: python manage.py runserver 0.0.0.0:8000